-- Create fines table for Azure SQL
CREATE TABLE IF NOT EXISTS fines (
  id INT IDENTITY(1,1) PRIMARY KEY,
  payer NVARCHAR(200) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  reason NVARCHAR(1000) NULL,
  created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
  paid BIT DEFAULT 0,
  paid_by NVARCHAR(200) NULL,
  paid_at DATETIMEOFFSET NULL
);
